# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/e610/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lge/e610/proprietary/bin/sensord:system/bin/sensord \
    vendor/lge/e610/proprietary/lib/hw/nfc.msm7x27a.so:system/lib/hw/nfc.msm7x27a.so \
    vendor/lge/e610/proprietary/lib/hw/sensors.m4.so:system/lib/hw/sensors.m4.so \
    vendor/lge/e610/proprietary/lib/libchromatix_hi542_default_video.so:system/lib/libchromatix_hi542_default_video.so \
    vendor/lge/e610/proprietary/lib/libchromatix_hi542_preview.so:system/lib/libchromatix_hi542_preview.so \
    vendor/lge/e610/proprietary/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so \
    vendor/lge/e610/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/lge/e610/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/lge/e610/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/lge/e610/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/lge/e610/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/lge/e610/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/lge/e610/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/lge/e610/proprietary/lib/liblgdrm.so:system/lib/liblgdrm.so \
    vendor/lge/e610/proprietary/lib/liblgeat.so:system/lib/liblgeat.so \
    vendor/lge/e610/proprietary/lib/liblge_security.so:system/lib/liblge_security.so \
    vendor/lge/e610/proprietary/lib/liblgsecclk.so:system/lib/liblgsecclk.so \
    vendor/lge/e610/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/lge/e610/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/lge/e610/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/lge/e610/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
